# ORDER MATTERS — first matching rule wins

rules:

  ########################################################
  # BROWSERS
  ########################################################
  - name: "Mozilla Firefox"
    match: "contains"
    pattern: "firefox"

  - name: "Google Chrome / Chromium"
    match: "contains_any"
    patterns: ["chrome", "chromium"]

  - name: "Microsoft Edge"
    match: "contains"
    pattern: "edge"

  ########################################################
  # ADOBE (ACROBAT, CC, LEGACY RUNTIMES)
  ########################################################
  - name: "Adobe Acrobat / Reader"
    match: "startswith_any"
    patterns:
      - "adobe:acrobat"
      - "adobe:acrobat_reader"

  - name: "Adobe Creative Cloud Apps"
    match: "startswith_any"
    patterns:
      - "adobe:photoshop"
      - "adobe:illustrator"
      - "adobe:indesign"
      - "adobe:media_encoder"
      - "adobe:premiere_pro"
      - "adobe:premiere_pro_cc"
      - "adobe:digital_editions"
      - "adobe:lightroom"
      - "adobe:creative_cloud"

  - name: "Adobe Legacy Runtimes"
    match: "startswith_any"
    patterns:
      - "adobe:air"
      - "adobe:flash_player"
      - "adobe:shockwave_player"
      - "adobe:svg_viewer"

  ########################################################
  # JAVA / RUNTIMES
  ########################################################
  - name: "Java Runtime (JRE/JDK)"
    match: "contains_any"
    patterns:
      - "oracle:jre"
      - "oracle:jdk"
      - "jdk "
      - "jre "
      - "java runtime"
      - "corretto"

  ########################################################
  # WEB SERVERS & CONFIG
  ########################################################
  - name: "Web Server Configuration Weakness"
    match: "startswith_any"
    patterns:
      - "Web Servers -"
      - "Web Server -"
      - "Web Servers :"
      - "CGI abuses"

  - name: "Apache HTTP Server"
    match: "startswith"
    pattern: "apache:http_server"

  - name: "Apache Tomcat"
    match: "contains"
    pattern: "apache:tomcat"

  ########################################################
  # MICROSOFT O/S (CLIENT + SERVER)
  ########################################################
  - name: "Microsoft Windows OS - Client"
    match: "contains_any"
    patterns:
      - "microsoft:windows_10"
      - "microsoft:windows_11"
      - "microsoft:windows_7"
      - "microsoft:windows_8"
      - "microsoft:windows_subsystem_for_linux"
      - "windows:terminal"
      - "microsoft:3d_builder"
      - "microsoft:3d_viewer"
      - "microsoft:snip_and_sketch"

  - name: "Microsoft Windows OS - Server"
    match: "startswith_any"
    patterns:
      - "microsoft:windows_server_"
      - "microsoft:azure_stack_hci"

  - name: "Microsoft Windows OS (Generic)"
    match: "startswith"
    pattern: "microsoft:windows"

  ########################################################
  # MICROSOFT OFFICE / COLLAB / DEV / DATA
  ########################################################
  - name: "Microsoft Office Desktop Apps"
    match: "startswith_any"
    patterns:
      - "microsoft:access"
      - "microsoft:onenote"
      - "microsoft:project_server"
      - "microsoft:powerpoint"
      - "microsoft:publisher"
      - "microsoft:visio"
      - "microsoft:visio_viewer"
      - "microsoft:infopath"

  - name: "Microsoft Collaboration Apps"
    match: "startswith_any"
    patterns:
      - "microsoft:teams"
      - "microsoft:skype_for_business"
      - "microsoft:lync_basic"
      - "microsoft:live_meeting"

  - name: "Microsoft SQL & Data Platform"
    match: "startswith_any"
    patterns:
      - "microsoft:sql_server"
      - "microsoft:sql_server_management_studio"
      - "microsoft:sql_server_reporting_services"
      - "microsoft:azure_devops_server"
      - "microsoft:endpoint_configuration_manager"

  - name: "Microsoft Codec / Video Extensions"
    match: "startswith_any"
    patterns:
      - "microsoft:hevc_video_extensions"
      - "microsoft:high_efficiency_video_coding"
      - "microsoft:vp9_extensions"
      - "microsoft:vp9_video_extensions"
      - "microsoft:web_media_extensions"
      - "microsoft:webp_image_extension"

  - name: "Microsoft Developer Tools"
    match: "startswith_any"
    patterns:
      - "microsoft:visual_studio"
      - "microsoft:visual_studio_code"
      - "microsoft:visual_basic"
      - "microsoft:visual_studio_tools_for_applications"

  - name: "Microsoft Security Components"
    match: "startswith_any"
    patterns:
      - "microsoft:malware_protection_engine"
      - "microsoft:system_center_endpoint_protection"
      - "microsoft:windows_defender"
      - "microsoft:remote_desktop"
      - "microsoft:remote_desktop_protocol"
      - "microsoft:message_queuing"

  ########################################################
  # DELL PLATFORM
  ########################################################
  - name: "Dell BIOS / Firmware"
    match: "startswith_any"
    patterns:
      - "dell:bios"
      - "dell:emc_idrac8"
      - "dell:emc_idrac9"
      - "dell:idrac9"
      - "dell:remote_access_card"

  - name: "Dell Utilities / Client Platform Tools"
    match: "startswith_any"
    patterns:
      - "dell:display_manager"
      - "dell:peripheral_manager"
      - "dell:trusted_device_agent"
      - "dell:dbutil"

  ########################################################
  # CITRIX / VDI
  ########################################################
  - name: "Citrix Workspace / VDI"
    match: "startswith_any"
    patterns:
      - "citrix:workspace"
      - "citrix:virtual_apps_and_desktops"

  ########################################################
  # CISCO / FORTINET / NETWORK OS
  ########################################################
  - name: "Cisco Network OS / Appliances"
    match: "startswith_any"
    patterns:
      - "cisco:ios"
      - "cisco:ios_xe"
      - "cisco:access_points"
      - "cisco:wireless_lan_controller_software"
      - "CISCO - Unsupported Cisco Operating System"

  - name: "Cisco Collaboration (Webex / Jabber / TelePresence)"
    match: "contains_any"
    patterns:
      - "cisco:jabber"
      - "cisco:webex"
      - "cisco:telepresence"

  - name: "Fortinet FortiClient"
    match: "startswith"
    pattern: "fortinet:forticlient"

  ########################################################
  # REMOTE ACCESS / SSH / FILE TRANSFER
  ########################################################
  - name: "Remote Support / Remote Admin"
    match: "contains_any"
    patterns:
      - "dameware"
      - "teamviewer"
      - "ultravnc"
      - "VNC Server Unauthenticated Access"

  - name: "SSH / Terminal Clients"
    match: "contains_any"
    patterns:
      - "putty"
      - "securecrt"
      - "openssh"
      - "dropbear_ssh"

  - name: "SFTP / File Transfer Tools"
    match: "contains_any"
    patterns:
      - "winscp"
      - "winrar"
      - "filezilla"

  - name: "VPN Clients"
    match: "contains_any"
    patterns:
      - "openvpn"
      - "globalprotect"
      - "forticlient"

  ########################################################
  # DATABASES
  ########################################################
  - name: "Oracle Database"
    match: "startswith"
    pattern: "oracle:database_server"

  - name: "MySQL / MariaDB"
    match: "contains_any"
    patterns:
      - "oracle:mysql"
      - "mysql:mysql_workbench"

  - name: "PostgreSQL"
    match: "startswith"
    pattern: "postgresql:postgresql"

  ########################################################
  # SSL / TLS / CERTIFICATE FINDINGS
  ########################################################
  - name: "SSL/TLS & Certificate Hygiene"
    match: "contains_any"
    patterns:
      - "General - SSL"
      - "TLS Version"
      - "openssl"
      - "md5"
      - "SSLv3"
      - "POODLE"

  ########################################################
  # NETWORK / INFRASTRUCTURE WEAKNESSES
  ########################################################
  - name: "Network Protocol / Infrastructure Issues"
    match: "contains_any"
    patterns:
      - "DNS -"
      - "SNMP -"
      - "SCADA -"
      - "NTP"
      - "ICMP"
      - "Backdoors -"
      - "SSH Weak"
      - "Telnet"
      - "X Server"
      - "mDNS"

  ########################################################
  # IMAGING / PDF / UTILITIES
  ########################################################
  - name: "PDF Viewers / Renderers"
    match: "contains_any"
    patterns:
      - "foxit"
      - "ghostscript"

  - name: "Imaging / Graphics Tools"
    match: "contains_any"
    patterns:
      - "imagemagick"
      - "greenshot"
      - "irfanview"

  ########################################################
  # DEV RUNTIMES / SCRIPTING
  ########################################################
  - name: "Developer Runtime Tools"
    match: "contains_any"
    patterns:
      - "node.js"
      - "python"
      - "jquery"
      - "git_for_windows"
      - "node-tar"
      - "r-project"

  ########################################################
  # MEDIA / VIDEO / ZOOM
  ########################################################
  - name: "Zoom"
    match: "contains_any"
    patterns:
      - "zoom:zoom"
      - "zoom:meetings"
      - "zoom:zoom_cloud_meetings"

  - name: "Media Players / Codec Apps"
    match: "contains_any"
    patterns:
      - "itunes"
      - "quicktime"
      - "vlc_media_player"
      - "geforce_experience"
      
  ########################################################
  # MICROSOFT .NET / DATA / SYSINTERNALS
  ########################################################
  - family: "Microsoft .NET / ASP.NET"
    match_any:
      - "microsoft:.net_core"
      - "microsoft:asp.net_core"
      - "microsoft:.net_framework"

  - family: "Microsoft SQL / Data Tools"
    match_any:
      - "microsoft:ole_db_driver_for_sql_server"
      - "Windows - Microsoft Azure Data Studio"

  - family: "Microsoft XML Core Services"
    match_any:
      - "microsoft:xml_core_services"

  - family: "Microsoft Sysinternals / Sysmon"
    match_any:
      - "Sysinternals Sysmon"

  ########################################################
  # MICROSOFT OFFICE & COLLAB – CORE APPS
  ########################################################
  - family: "Microsoft Office - Core Apps"
    match_any:
      - "microsoft:office"
      - "microsoft:excel"
      - "microsoft:word"
      - "microsoft:outlook"
      - "microsoft:office_compatibility_pack"
      - "microsoft:office_web_apps"
      - "microsoft:office_online_server"
      - "microsoft:sharepoint_server"

  ########################################################
  # VMWARE PLATFORM
  ########################################################
  - family: "VMware vSphere / ESXi / Tools"
    match_any:
      - "vmware:tools"
      - "vmware:esxi"
      - "vmware:esx_server"
      - "vmware:vcenter_server"
      - "vmware:vsphere_client"

  ########################################################
  # DELL SUPPORTASSIST / OS RECOVERY
  ########################################################
  - family: "Dell SupportAssist / OS Recovery"
    match_any:
      - "dell:supportassist"
      - "Dell SupportAssist OS Recovery Information Disclosure"
      - "Dell SupportAssist OS Recovery Multiple Vulnerabilities"
      - "Dell SupportAssist OS Recovery Symbolic Link Attack"
      - "DSA-2025-403"
      - "DSA-2025-315"
      - "DSA-2025-051"

  ########################################################
  # INTEL PLATFORM DRIVERS
  ########################################################
  - family: "Intel Platform Drivers"
    match_any:
      - "intel:chipset_device_software"
      - "intel:dynamic_tuning_technology"

  ########################################################
  # ENDPOINT SECURITY (AV / EDR)
  ########################################################
  - family: "Endpoint Security (AV / EDR)"
    match_any:
      - "symantec:endpoint_protection"
      - "sophos:sophos_anti-virus"
      - "CrowdStrike Falcon Sensor"

  ########################################################
  # VULNERABILITY / MGMT AGENTS
  ########################################################
  - family: "Vulnerability Scanners / Agents"
    match_any:
      - "tenable:nessus_agent"

  ########################################################
  # UTILITIES – ARCHIVE / EDITORS / NETWORK TOOLS
  ########################################################
  - family: "Utilities - Archive / Editors"
    match_any:
      - "7-zip:7-zip"
      - "notepad-plus-plus:notepad"
      - "rarlab:winrar"

  - family: "Network Tools - Wireshark"
    match_any:
      - "wireshark:wireshark"

  ########################################################
  # WEB / MIDDLEWARE STACKS
  ########################################################
  - family: "Java / Middleware - Log4j"
    match_any:
      - "apache:log4j"

  - family: "Web Servers / Proxies"
    match_any:
      - "nginx:nginx"
      - "allegro:rom_pager"

  ########################################################
  # LINUX / UNIX SERVER OS
  ########################################################
  - family: "Linux / Unix Server OS"
    match_any:
      - "oracle:linux"
      - "debian:debian_linux"
      - "canonical:ubuntu_linux"
      - "centos:centos"

  ########################################################
  # PRINT / DOC MANAGEMENT
  ########################################################
  - family: "Print & Document Management"
    match_any:
      - "papercut:papercut_mf"

  ########################################################
  # REMOTE ADMIN – EXTRA
  ########################################################
  - family: "Remote Admin / Screen Sharing"
    match_any:
      - "Windows - Devolutions Remote Desktop Manager"

  ########################################################
  # HPE / ILO
  ########################################################
  - family: "HPE iLO / Lights-Out Firmware"
    match_any:
      - "hp:integrated_lights-out_firmware"

  ########################################################
  # WINDOWS CONFIG / HARDENING
  ########################################################
  - family: "Windows Configuration / Hardening Findings"
    match_any:
      - "Windows - Microsoft Windows Unquoted Service Path Enumeration"
      - "Windows - Microsoft Windows SMB Registry"
      - "Windows - Microsoft Windows Update Reboot Required"
      - "Windows - SizerOne ActiveX Control AddTab Method Remote Buffer Overflow"
      - "Misc. - LOLDriver Detection (Windows)"

  ########################################################
  # NETWORK / INFRA FINDINGS – EXTRA
  ########################################################
  - family: "Network Protocol / Infra Issues"
    match_any:
      - "Misc. - AMQP Cleartext Authentication"


defaults:
  vendor_from_prefix: true
  unknown_family_name: "Other / Misc"

